CREATE TABLE IF NOT EXISTS system_calendar.auth_code (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    used_for text NOT NULL
);
ALTER TABLE system_calendar.auth_code ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON system_calendar.auth_code FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA system_calendar TO service_role;
GRANT SELECT ON system_calendar.auth_code TO service_role;
CREATE INDEX IF NOT EXISTS auth_code_current_access_idx
    ON system_calendar.auth_code (created_at DESC, id DESC) WHERE used_for = 'access';
NOTIFY pgrst, 'reload schema';
